<?php require APP_ROOT.'/views/'.APP_THEME.'/top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="app">
    <?php require APP_ROOT.'/views/'.APP_THEME.'/head.phtml';?>
    <?php require APP_ROOT.'/views/'.APP_THEME.'/left.phtml';?>
    <main class="app-main">
        <div class="wrapper">
          <div class="page">
            <div class="page-inner">
              <?php require APP_ROOT.'/views/'.APP_THEME.'/table.phtml';?>
            </div>
          </div>
        </div>
        <?php require APP_ROOT.'/views/'.APP_THEME.'/foot.phtml';?>
    </main>
</div>
<script type="text/javascript">advanceDataTables.init('/api/lang/v1/', [<?php echo join(',', array_map('json_encode', $this->fieldsList));?>]);</script>
<?php require APP_ROOT.'/views/'.APP_THEME.'/bottom.phtml';?>