<?php require __DIR__.'/../top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="app">
    <?php require __DIR__.'/../head.phtml';?>
    <?php require __DIR__.'/../left.phtml';?>
    <main class="app-main">
        <div class="wrapper">
          <div class="page">
            <div class="page-inner">
              <?php require __DIR__.'/../form.phtml';?>
            </div>
          </div>
        </div>
        <?php require __DIR__.'/../foot.phtml';?>
    </main>
</div>
<?php require __DIR__.'/../bottom.phtml';?>