#!/bin/sh
service openresty start

service php8.1-fpm start

service redis-server start

service rabbitmq-server start

mysqld --user=root &

mongod -f /etc/mongod.conf &

supervisord -c /etc/supervisord.conf

composer update

php app/admin/bin/install.php
php app/iot/bin/install.php
php app/paas/bin/install.php
php app/payment/bin/install.php
php app/store/bin/install.php

zsh
