<?php require APP_ROOT.'/views/'.APP_THEME.'/top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="app">
    <?php require APP_ROOT.'/views/'.APP_THEME.'/head.phtml';?>
    <?php require APP_ROOT.'/views/'.APP_THEME.'/left.phtml';?>
    <main class="app-main">
        <div class="wrapper">
          <div class="page">
            <div class="page-inner">
              <?php require APP_ROOT.'/views/'.APP_THEME.'/table.phtml';?>
            </div>
          </div>
        </div>
        <?php require APP_ROOT.'/views/'.APP_THEME.'/foot.phtml';?>
    </main>
</div>
<script type="text/javascript">advanceDataTables.init('/api/config/v1/', [
{data:'id', className:'col-checker align-middle', orderable: false, searchable: false},
{title:'app_id', data:'app_id', className:'align-middle'},
{title:'date_add', data:'date_add', render: function c(data){return timeStampToDate(data);}, className:'align-middle'},
{title:'date_upd', data:'date_upd', render: function c(data){return timeStampToDate(data);}, c:'align-middle'},
{title:'name', data:'name', className:'align-middle'},
{title:'value', data:'value', className:'align-middle'},
{data:'id', className:'align-middle text-right', orderable: false, searchable: false}
]);</script>
<?php require APP_ROOT.'/views/'.APP_THEME.'/bottom.phtml';?>