<?php require APP_ROOT.'/views/'.APP_THEME.'/top.phtml';?>

<link href="css/login.css" rel="stylesheet" />
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
	<h1><?php echo $this->test;?></h1>
<?php require APP_ROOT.'/views/'.APP_THEME.'/bottom.phtml';?>