<?php require __DIR__ . '/../top.phtml'; ?>
<title><?php echo $this->title; ?></title>
<meta name="description" content="<?php echo $this->description; ?>"/>
<meta name="keywords" content="<?php echo $this->keywords; ?>"/>
<link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style"/>
</head>
<body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'>
<div class="auth-fluid">
    <div class="auth-fluid-form-box">
        <div class="align-items-center d-flex h-100">
            <div class="card-body">
                <div class="auth-brand text-center text-lg-start">
                    <a href="javascript: void(0);" class="logo-dark">
                        <span><img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" height="18"></span>
                    </a>
                    <a href="javascript: void(0);" class="logo-light">
                        <span><img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" height="18"></span>
                    </a>
                </div>
                <h4 class="mt-0">Free Sign Up</h4>
                <p class="text-muted mb-4">Don't have an account? Create your account, it takes less than a minute</p>
                <form action="#">
                    <div class="mb-3">
                        <label for="fullname" class="form-label">Full Name</label>
                        <input class="form-control" type="text" id="fullname" placeholder="Enter your name" required>
                    </div>
                    <div class="mb-3">
                        <label for="emailaddress" class="form-label">Email address</label>
                        <input class="form-control" type="email" id="emailaddress" required placeholder="Enter your email">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <div class="input-group input-group-merge">
                            <input class="form-control" type="password" id="pass" name="pass" required placeholder="Enter your password">
                            <div class="input-group-text" data-password="false">
                                <span class="password-eye"></span>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="checkbox-signup">
                            <label class="form-check-label" for="checkbox-signup">I accept <a href="javascript: void(0);" class="text-muted">Terms and Conditions</a></label>
                        </div>
                    </div>
                    <div class="mb-0 d-grid text-center">
                        <button class="btn btn-primary" type="submit"><i class="mdi mdi-account-circle"></i> Sign Up </button>
                    </div>
                    <div class="text-center mt-4">
                        <p class="text-muted font-16">Sign up using</p>
                        <ul class="social-list list-inline mt-3">
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-primary text-primary"><i class="mdi mdi-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-danger text-danger"><i class="mdi mdi-google"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-info text-info"><i class="mdi mdi-twitter"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="javascript: void(0);" class="social-list-item border-secondary text-secondary"><i class="mdi mdi-github"></i></a>
                            </li>
                        </ul>
                    </div>
                </form>
                <footer class="footer footer-alt">
                    <p class="text-muted">Already have account? <a href="/login" class="text-muted ms-1"><b>Log In</b></a></p>
                </footer>
            </div>
        </div>
    </div>
    <div class="auth-fluid-right text-center">
        <div class="auth-user-testimonial">
            <h2 class="mb-3">I love the HookPHP!</h2>
            <p class="lead"><i class="mdi mdi-format-quote-open"></i> <?php echo $this->title;?>! . <i class="mdi mdi-format-quote-close"></i></p>
            <p>- LetWang</p>
        </div>
    </div>
</div>
<script src="/assets/js/vendor.min.js"></script>
<script src="/assets/js/app.min.js"></script>
<script>
    $('.needs-validation').submit(function (event) {
        event.preventDefault();
        if (!$(this)[0].checkValidity()) {
            event.stopPropagation();
        } else {
            $.ajax({
                method: 'POST',
                url: '/api/login/v1',
                data: {
                    user: $("input[name='user']").val(),
                    pass: $("input[name='pass']").val(),
                    token: $("input[name='token']").val(),
                    referer: $("input[name='referer']").val(),
                    remember: $("input[name='remember']").val()
                },
                dataType: 'json'
            }).done(function(data, textStatus, jqXHR) {
                if (data.code === 'ok') {
                    $('#alert').html('<div class="alert alert-success alert-dismissible" role="alert">'+data.msg+'<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');
                    location.href = data.data.referer;
                } else {
                    $('#alert').html('<div class="alert alert-danger alert-dismissible" role="alert">'+data.msg+'<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>');
                }
            }).fail(function(jqXHR, textStatus, errorThrown) {
                $('#alert').html('<div class="alert alert-dark alert-dismissible" role="alert">'+textStatus+'<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>')
            });
        }
        $(this).addClass('was-validated');
    });
</script>
<?php require __DIR__ . '/../bottom.phtml'; ?>