<?php
use Hook\Form\Form;

require APP_PATH.'/layout/top.phtml';
?>

<link href="css/login.css" rel="stylesheet" />
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="container">
	<?php echo Form::form('acl', '/adminaclresource', 'post', 'class="needs-validation" novalidate');?>
	<div class="form-group">
	<?php echo Form::label('app').Form::input('app', '', 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<div class="form-group">
	<?php echo Form::label('module').Form::input('module', '', 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<div class="form-group">
	<?php echo Form::label('controller').Form::input('controller', '', 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<div class="form-group">
	<?php echo Form::label('action').Form::input('action', '', 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<div class="form-group">
	<?php echo Form::label('status').Form::select('status', [0, 1], 1, 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<div class="form-group">
	<?php echo Form::label('name').Form::input('name', '', 'required class="form-control"');?>
	<div class="invalid-feedback"><?php echo l('tips.required')?></div>
	</div>
	<?php echo Form::submit('submit', 'class="btn btn-primary"');?>
	</form>
</div>
<?php require APP_PATH.'/layout/foot.phtml';?>