<div class="form-group">
  <div class="input-group input-group-alt" data-toggle="colorpicker">
    <input id="<?php echo $input['id'];
    ?>" name="<?php echo $input['name'];
    ?>" type="text" class="form-control <?php echo $input['class'] ?? '';
    ?>" value="<?php echo $this->fieldsValue[$input['name']] ?? '';
    ?>">
    <span class="input-group-append"><span class="input-group-text colorpicker-input-addon"><i class="align-self-center"></i></span></span>
  </div>
</div>