<div class="form-group">
  <div class="input-group input-group-alt flatpickr" data-toggle="flatpickr" data-wrap="true">
    <input id="<?php echo $input['id'] ?? $input['name'];
    ?>" name="<?php echo $input['name'];
    ?>" class="form-control <?php echo $input['class'] ?? '';
    ?>" value="<?php echo $this->value[$input['name']] ?? '';
    ?>" type="text" data-input="" />
    <div class="input-group-append">
      <button type="button" class="btn btn-secondary" data-toggle=""><i class="far fa-calendar"></i></button>
      <button type="button" class="btn btn-secondary" data-clear=""><i class="fa fa-times"></i></button>
    </div>
  </div>
</div>