<div class="input-group input-group-alt">
<span class="input-group-prepend"><span class="input-group-text"><span class="oi oi-eye"></span></span></span>
<input type="number" id="<?php echo $input['id'] ?? $input['name'];
?>" name="<?php echo $input['name'];
?>" class="form-control <?php echo $input['class'] ?? '';
?>" value="<?php
echo $this->value[$input['name']] ?? '';?>"<?php
if (empty($input['autocomplete'])) {?> autocomplete="off"<?php }
if (!empty($input['required'])) {?> required<?php }?> />
</div>