<?php
foreach($input['values'] as $value) {
?>
<div class="custom-control custom-radio <?php
    echo (empty($value['tips']) ? 'custom-control-inline' : '').' '.$input['class'] ?? '';?>">
    <input type="radio" name="<?php echo $input['name'];
    ?>" class="custom-control-input" id="<?php echo $input['name'].'_'.$value['value'];
    ?>" value="<?php echo $value['value'];
    ?>"<?php
    if ($this->value[$input['name']] ?? '' === $value['value']) {?> checked="checked"<?php }
    if (!empty($value['disabled'])) {?> disabled="disabled"<?php }
    ?>/> <label class="custom-control-label" for="<?php
    echo $input['name'].'_'.$value['value'];?>"><?php
    echo $value['label'] ?? '';?></label>
</div>
<?php
    if (isset($value['tips'])) {?><div class="text-muted"><?php echo $value['tips'];?></div><?php }
}