<label class="switcher-control" for="<?php echo $input['name'];?>">
        <input class="switcher-input <?php echo $input['class'] ?? '';
        ?>" type="checkbox" name="<?php echo $input['name'];
        ?>" id="<?php echo $input['name'];
        ?>" value="1"<?php
        if (!empty($this->fieldsValue[$input['name']])) {?> checked="checked"<?php }?>/>
<span class="switcher-indicator"></span>
</label>