<aside class="app-aside">
<div class="aside-content">
  <header class="aside-header d-block d-md-none">
    <button class="btn-account" type="button" data-toggle="collapse" data-target="#dropdown-aside">
      <span class="user-avatar user-avatar-lg">
        <img src="assets/images/avatars/profile.jpg" alt="">
      </span>
      <span class="account-icon">
        <span class="fa fa-caret-down fa-lg"></span>
      </span>
      <span class="account-summary">
        <span class="account-name">Beni Arisandi</span>
        <span class="account-description">Marketing Manager</span>
      </span>
    </button>
    <div id="dropdown-aside" class="dropdown-aside collapse">
      <div class="pb-3">
        <a class="dropdown-item" href="">
          <span class="dropdown-icon oi oi-person"></span> Profile</a>
        <a class="dropdown-item" href="login/out/">
          <span class="dropdown-icon oi oi-account-logout"></span> Logout</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Help Center</a>
        <a class="dropdown-item" href="#">Ask Forum</a>
        <a class="dropdown-item" href="#">Keyboard Shortcuts</a>
      </div>
    </div>
  </header>
  <section class="aside-menu has-scrollable">
    <nav id="stacked-menu" class="stacked-menu">
      <ul class="menu">
        <li class="menu-item has-active">
          <a href="" class="menu-link">
            <span class="menu-icon oi oi-dashboard"></span>
            <span class="menu-text">Dashboard</span>
            <span class="badge badge-success">20+</span>
          </a>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-people"></span>
            <span class="menu-text">用户管理</span>
            <span class="badge badge-warning">New</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">Blank Page</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-puzzle-piece"></span>
            <span class="menu-text">资源管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-pencil"></span>
            <span class="menu-text">角色管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-grid-two-up"></span>
            <span class="menu-text">权限管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-bar-chart"></span>
            <span class="menu-text">配置管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-list-rich"></span>
            <span class="menu-text">翻译管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-wrench"></span>
            <span class="menu-text">SEO管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-browser"></span>
            <span class="menu-text">菜单管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-infinity"></span>
            <span class="menu-text">语言管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-media-skip-backward"></span>
            <span class="menu-text">模块管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-resize-both"></span>
            <span class="menu-text">模板管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-link-broken"></span>
            <span class="menu-text">终端管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
        <li class="menu-item has-child">
          <a href="#" class="menu-link">
            <span class="menu-icon oi oi-signpost"></span>
            <span class="menu-text">平台管理</span>
          </a>
          <ul class="menu">
            <li class="menu-item">
              <a href="" class="menu-link">General</a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </section>
</div>
</aside>