<?php require APP_PATH.'/views/'.THEME_NAME.'/top.phtml';?>

<link href="css/login.css" rel="stylesheet" />
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
	<h1><a href="login/out/">OK.</a></h1>
<?php require APP_PATH.'/views/'.THEME_NAME.'/bottom.phtml';?>