<?php echo \Hook\Hook\Hook::run('displayFoot');?>
<script>
(function() {
  'use strict';
  window.addEventListener('load', function() {
    var forms = document.getElementsByClassName('needs-validation');
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
<?php
$data = [];
foreach (APP_CONFIG['regexp']['core'] as $key => $value) {
    $data[] = $key.':/'.$value.'/';
}
echo 'var config = {regexp:{',join(',', $data),'}};';
?>

</script>
<script src="assets/vendor/jquery/jquery.min.js"></script><script src="assets/vendor/bootstrap/js/popper.min.js"></script><script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/vendor/stacked-menu/stacked-menu.min.js"></script><script src="assets/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="assets/javascript/main.min.js"></script>
</body>
</html>