<?php echo \Hook\Hook\Hook::run('displayFoot');?>
<script>
function timeStampToDate(timeStamp) {
    var date = new Date();
    date.setTime(timeStamp * 1000);
    var y = date.getFullYear();
    var m = date.getMonth() + 1;
    m = m < 10 ? ('0' + m) : m;
    var d = date.getDate();
    d = d < 10 ? ('0' + d) : d;
    var h = date.getHours();
    h = h < 10 ? ('0' + h) : h;
    var minute = date.getMinutes();
    var second = date.getSeconds();
    minute = minute < 10 ? ('0' + minute) : minute;
    second = second < 10 ? ('0' + second) : second;
    return y + '-' + m + '-' + d+' '+h+':'+minute+':'+second;
};
<?php
$data = [];
foreach (APP_CONFIG['regexp']['core'] as $key => $value) {
    $data[] = $key.':/'.$value.'/';
}
echo 'var config = {regexp:{',join(',', $data),'}};';
?>
</script>
<script src="https://cdn.bootcss.com/popper.js/1.14.4/umd/popper.min.js"></script><script src="https://cdn.bootcss.com/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script><script src="https://cdn.bootcss.com/jquery.perfect-scrollbar/1.4.0/perfect-scrollbar.min.js"></script>
<script src="/assets/vendor/stacked-menu/stacked-menu.min.js"></script><script src="/assets/javascript/main.min.js"></script>
</body>
</html>