<?php
$langCount = count($this->languages);
if (isset($this->fields['title'])) {?><h3><?php echo $this->fields['title'];?></h3><?php }?>
<form id="<?php echo $this->controller;
?>_form" class="defaultForm form-horizontal <?php echo $this->controller;
?>" action="/api/<?php echo $this->controller;?>/v1/<?php echo $this->id ? 'id/'.$this->id: '';
?>" method="<?php echo $this->id ? 'PUT' : 'POST';
?>" enctype="multipart/form-data" novalidate>
<?php foreach($this->fields['data'] ?? [] as $index => $fieldSet) {?>
<div class="panel" id="fieldSet_<?php echo $index;?>_0_0">
<?php foreach($fieldSet['form'] as $key => $field) {

////////////////////////////////////////////////////// one
if ($key === 'legend') {?>
<div class="panel-heading"><?php
if (isset($field['image']) && isset($field['title'])) {
?><img src="<?php echo $field['image'];?>" alt="<?php echo $field['title'];?>" /><?php
}
if (isset($field['icon'])) {
?><i class="<?php echo $field['icon'];?>"></i><?php
}
echo $field['title'];?></div>
<?php

////////////////////////////////////////////////////// two
} elseif ($key === 'description'){?>
<div class="alert alert-info"><?php echo $field;?></div>
<?php

////////////////////////////////////////////////////// three
}elseif ($key === 'warning'){?>
<div class="alert alert-warning"><?php echo $field;?></div>
<?php

////////////////////////////////////////////////////// four
}elseif ($key === 'success'){?>
<div class="alert alert-success"><?php echo $field;?></div>
<?php

////////////////////////////////////////////////////// five
}elseif ($key === 'error'){?>
<div class="alert alert-danger"><?php echo $field;?></div>
<?php

////////////////////////////////////////////////////// six
} elseif ($key === 'desc') {?>
<div class="alert alert-info col-lg-offset-3">
<?php
    if (is_array($field)) {
        foreach($field as $key => $value) {
            if (is_array($value)) {?>
<span<?php
                if (isset($value['id'])) {?> id="<?php
                    echo $value['id'];?>"<?php
                }
?>><?php
                    echo $value['text'];?></span><br />
<?php       } else {
                    echo $value;
                    if (isset($field[$key+1])) {?><br /><?php }
            }
        }
    } else {
        echo $field;
    }
?>
</div>
<?php

////////////////////////////////////////////////////// seven
}elseif ($key === 'input'){?>
<div class="form-wrapper">
<?php foreach($field as $input) {?>
<div class="form-group <?php echo $input['class'] ?? '';
if ($input['type'] === 'hidden') {?> hide<?php }?>">
<?php

//**************************************************** 1
if ($input['type'] === 'hidden') {?>
<input type="hidden" name="<?php echo $input['name'];
?>" id="<?php echo $input['name'];
?>" value="<?php echo $this->fieldsValue[$input['name']] ?? '';?>" />
<?php
} else {
    if (isset($input['label'])) {?>
<label class="control-label col-lg-3<?php
if (!empty($input['required']) && $input['type'] !== 'radio') {?> required<?php }?>"><?php
if (isset($input['hint'])) {?><span class="label-tooltip" data-toggle="tooltip" data-html="true" title="<?php
    foreach((array) $input['hint'] as $value) {
        echo $value;
    }?>"><?php
}
echo $input['label'];
if (isset($input['hint'])) {?></span><?php }?></label>
<?php }?>
<div class="col-lg-<?php echo $input['col'] ?? 9;if (!isset($input['label'])) {?> col-lg-offset-3<?php }?>">
<?php

//**************************************************** 2
if ($input['type'] === 'text') {
    if ($langCount > 1) {?>
<div class="form-group">
<?php
    }
    foreach($this->languages as $language) {
        if ($langCount > 1) {?>
<div class="row lang-<?php echo $language['id'];
?>" <?php if ((int) $language['id'] !== APP_LANG) {?>style="display:none"<?php }?>>
<div class="col-lg-9"><?php
        }
        if (isset($input['maxchar']) || isset($input['prefix']) || isset($input['suffix'])) {?>
<div class="input-group input-group-alt <?php echo $input['class'] ?? '';?>">
<?php
        }
        if (isset($input['maxchar'])) {?>
<span id="<?php echo ($input['id'] ?? $input['name']).'_'.$language['id'];?>_counter" class="input-group-prepend">
	<span class="input-group-text"><?php echo $input['maxchar'];?></span>
</span>
<?php
        }
        if (isset($input['prefix'])) {?>
<div class="input-group-prepend"><span class="input-group-text"><?php echo $input['prefix'];?></span></div>
<?php
        }
?>
<input type="text" id="<?php echo ($input['id'] ?? $input['name']).$language['id'];
        ?>" name="<?php echo $input['name'].$language['id'];
        ?>" class="form-control <?php echo $input['class'] ?? '';
        ?>" value="<?php echo $this->fieldsValue[$input['name']][$language['id']] ?? '';?>" <?php
        if (isset($input['size'])) {?> size="<?php echo $input['size'];?>"<?php }
        if (isset($input['maxchar'])) {?> data-maxchar="<?php echo $input['maxchar'];?>"<?php }
        if (isset($input['maxlength'])) {?> maxlength="<?php echo $input['maxlength'];?>"<?php }
        if (!empty($input['readonly'])) {?> readonly="readonly"<?php }
        if (!empty($input['disabled'])) {?> disabled="disabled"<?php }
        if (empty($input['autocomplete'])) {?> autocomplete="off"<?php }
        if (!empty($input['required'])) {?> required="required"<?php }
        if (isset($input['placeholder'])) {?> placeholder="<?php echo $input['placeholder'];?>"<?php }?> />
<?php
        if (isset($input['suffix'])) {?>
<div class="input-group-append"><span class="input-group-text"><?php echo $input['suffix'];?></span></div>
<?php
        }
        if (isset($input['maxchar']) || isset($input['prefix']) || isset($input['suffix'])) {?>
</div>
<?php
        }
        if ($langCount > 1) {
    ?>
</div>
<div class="col-lg-3">
<div class="input-group-prepend dropdown">
  <button class="btn btn-default" type="button" data-toggle="dropdown"><?php
            echo $language['iso'];?> <span class="caret"></span></button>
  <div class="dropdown-arrow"></div>
  <div class="dropdown-menu"><?php
            foreach($this->languages as $language) {?>
<a class="dropdown-item" href="javascript:hideOtherLanguage(<?php echo $language['id'];?>);" tabindex="-1"><?php
                echo $language['name'];?></a><?php
            }
?>
  </div>
</div>
</div>
</div>
<?php
        }
    }
    if ($langCount > 1) {?>
</div>
<?php
    }

//**************************************************** 3
} elseif ($input['type'] === 'select') {?>
<select id="<?php echo $input['id'] ?? $input['name'];
    ?>" name="<?php echo $input['name'];
    ?>" class="custom-select <?php echo $input['class'] ?? '';?>"<?php
    if (!empty($input['multiple'])) {?> multiple="multiple"<?php }
    if (!empty($input['size'])) {?> size="<?php echo $input['size'];?>"<?php }
    if (isset($input['onchange'])) {?> onchange="<?php echo $input['onchange'];?>"<?php }
    if (!empty($input['disabled'])) {?> disabled="disabled"<?php }?>>
<?php
    foreach($input['values'] as $options) {
        if (isset($options['label'])) {?>
<optgroup label="<?php echo $options['label'];?>">
<?php
        }
        foreach($options['options'] as $key => $value) {?>
<option value="<?php echo $key;?>"<?php
            foreach($this->fieldsValue[$input['name']] ?? [] as $fieldValue) {
                if ($fieldValue === $key) {
?> selected="selected"<?php
                }
            }
?>><?php
            echo $value;?></option><?php
        }
        if (isset($options['label'])) {
?>
</optgroup>
<?php
        }
    }
?>
</select>
<?php

//**************************************************** 4
} elseif ($input['type'] === 'radio') {
    foreach($input['values'] as $value) {?>
<div class="custom-control custom-radio <?php
        echo (empty($value['tips']) ? 'custom-control-inline' : '').' '.$input['class'] ?? '';?>">
    <input type="radio" name="<?php echo $input['name'];
        ?>" class="custom-control-input" id="<?php echo $input['name'].'_'.$value['value'];
        ?>" value="<?php echo $value['value'];
        ?>"<?php
        if ($this->fieldsValue[$input['name']] ?? '' === $value['value']) {?> checked="checked"<?php }
        if (!empty($value['disabled'])) {?> disabled="disabled"<?php }
        ?>/> <label class="custom-control-label" for="<?php
        echo $input['name'].'_'.$value['value'];?>"><?php
        echo $value['label'] ?? '';?></label>
</div>
<?php
        if (isset($value['tips'])) {?><div class="text-muted"><?php echo $value['tips'];?></div><?php }
    }

//**************************************************** 5
} elseif ($input['type'] === 'switch') {?>
<label class="switcher-control" for="<?php echo $input['name'];?>">
        <input class="switcher-input <?php echo $input['class'] ?? '';
        ?>" type="checkbox" name="<?php echo $input['name'];
        ?>" id="<?php echo $input['name'];
        ?>" value="1"<?php
        if (!empty($this->fieldsValue[$input['name']])) {?> checked="checked"<?php }?>/>
<span class="switcher-indicator"></span>
</label>
<?php

//**************************************************** 6
} elseif ($input['type'] === 'textarea') {
    foreach($this->languages as $language) {
        if ($langCount > 1) {?>
<div class="form-group row lang-<?php echo $language['id'];?>"<?php
            if ((int) $language['id'] !== APP_LANG) {?> style="display:none;"<?php }?>>
<div class="col-lg-9">
<?php
        }
        if (isset($input['maxchar'])) {?>
<div class="input-group input-group-alt">
<span id="<?php echo ($input['id'] ?? $input['name']).'_'.$language['id'];?>_counter" class="input-group-prepend">
    <span class="input-group-text"><?php echo $input['maxchar'];?></span>
</span>
<?php
        }
?>
<textarea name="<?php echo $input['name'].'_'.$language['id'];
        ?>" id="<?php echo ($input['id'] ?? $input['name']).'_'.$language['id'];
        ?>" class="form-control <?php echo $input['class'] ?? '';
        ?>" <?php
        if (!empty($input['readonly'])) {?> readonly="readonly"<?php }
        if (isset($input['cols'])) {?> cols="<?php echo $input['cols'];?>"<?php }
        if (isset($input['rows'])) {?> rows="<?php echo $input['rows'];?>"<?php }
        if (isset($input['maxlength'])) {?> maxlength="<?php echo $input['maxlength'];?>"<?php }
        if (isset($input['maxchar'])) {?> data-maxchar="<?php echo $input['maxchar'];?>"<?php }?>><?php
        echo $this->fieldsValue[$input['name']][$language['id']] ?? '';?></textarea>
<?php
        if (isset($input['maxchar'])) {
?>
</div>
<?php
        }
        if ($langCount > 1) {?>
</div>
<div class="col-lg-3">
<div class="input-group-prepend dropdown">
  <button class="btn btn-default" type="button" data-toggle="dropdown"><?php
            echo $language['iso'];?> <span class="caret"></span></button>
  <div class="dropdown-arrow"></div>
  <div class="dropdown-menu"><?php
            foreach($this->languages as $language) {?>
<a class="dropdown-item" href="javascript:hideOtherLanguage(<?php echo $language['id'];?>);" tabindex="-1"><?php
                echo $language['name'];?></a><?php
            }
?>
  </div>
</div>
</div>
</div>
<?php
        }
    }

//**************************************************** 7
} elseif ($input['type'] === 'checkbox') {
    if (isset($input['expand'])) {?>
<a class="btn btn-default show_checkbox<?php if ($input['expand']['default'] === 'hide') {?> hidden<?php }?>" href="#">
<i class="icon-<?php echo $input['expand']['show']['icon'];?>"></i>
<?php
        echo $input['expand']['show']['text'];
        if (!empty($input['expand']['total'])) {?>
<span class="badge"><?php echo $input['expand']['total'];?></span>
<?php
        }
?>
</a>
<a class="btn btn-default hide_checkbox<?php if ($input['expand']['default'] === 'show') {?> hidden<?php }?>" href="#">
<i class="icon-<?php echo $input['expand']['hide']['icon'];?>"></i>
<?php
        echo $input['expand']['hide']['text'];
        if (!empty($input['expand']['total'])) {?>
<span class="badge"><?php echo $input['expand']['total'];?></span>
<?php
        }
?>
</a>
<?php
    }
    foreach($input['values'] as $value) {
        $idCheckbox = $input['name'].'_'.$value['value'];
?>
<div class="checkbox<?php if ($input['expand']['default'] ?? '' === 'show') {?> hidden<?php }?>">
<label for="<?php echo $idCheckbox;?>">
<input type="checkbox" name="<?php echo $input['name'].'[]';
        ?>" id="<?php echo $idCheckbox;
        ?>" class="<?php echo $input['class'] ?? '';
        ?>" value="<?php echo $value['value'];
        ?>"<?php
        if (isset($this->fieldsValue[$idCheckbox])) {?> checked="checked"<?php }?> />
<?php
        echo $value['label'];?></label></div>
<?php
    }

//**************************************************** 8
} elseif ($input['type'] === 'password') {?>
<div class="input-group input-group-alt">
<span class="input-group-prepend"><span class="input-group-text"><span class="oi oi-eye"></span></span></span>
<input type="password" id="<?php echo $input['id'] ?? $input['name'];
?>" name="<?php echo $input['name'];
?>" class="form-control <?php echo $input['class'] ?? '';
?>" value=""<?php
if (empty($input['autocomplete'])) {?> autocomplete="off"<?php }
if (!empty($input['required'])) {?> required="required"<?php }?> />
</div>
<?php

//**************************************************** 9
} elseif ($input['type'] === 'birthday') {?>
<div class="form-group">
<?php foreach($input['values'] as $key => $select) {?>
<div class="col-lg-2">
<select name="<?php echo $key;?>" class="fixed-width-lg <?php echo $input['class'] ?? '';?>">
<option value="">-</option>
<?php if ($key === 'month') {
          foreach($select as $k => $v) {
?><option value="<?php echo $k;?>"<?php if ($this->fieldsValue[$key] ?? '' === $k) {?> selected="selected"<?php }
?>><?php
              echo $v;?></option><?php
          }
      } else {
          foreach($select as $v) {
?><option value="<?php echo $v;?>"<?php if ($this->fieldsValue[$key] ?? '' === $v) {?> selected="selected"<?php }
?>><?php
              echo $v;?></option><?php
          }
      }
?></select></div>
<?php }?>
</div>
<?php

//**************************************************** 10
} elseif ($input['type'] === 'color') {?>
<div class="form-group">
<div class="col-lg-2">
<div class="row">
<div class="input-group">
<input type="color" data-hex="true" class="<?php echo $input['class'] ?? 'color mColorPickerInput';
?>" id="<?php echo $input['id'];
?>" name="<?php echo $input['name'];
?>" value="<?php echo $this->fieldsValue[$input['name']] ?? '';?>" />
</div>
</div>
</div>
</div>
<?php

//**************************************************** 11
} elseif ($input['type'] === 'date') {?>
<div class="row">
<div class="input-group col-lg-4">
<input id="<?php echo $input['id'] ?? $input['name'];
?>" type="text" data-hex="true" class="<?php echo $input['class'] ?? 'datepicker';
?>" name="<?php echo $input['name'];
?>" value="<?php echo $this->fieldsValue[$input['name']] ?? '';?>" />
<span class="input-group-addon"><i class="icon-calendar-empty"></i></span>
</div>
</div>
<?php

//**************************************************** 12
} elseif ($input['type'] === 'datetime') {?>
<div class="row">
<div class="input-group col-lg-4">
<input id="<?php echo $input['id'] ?? $input['name'];
?>" type="text" data-hex="true" class="<?php echo $input['class'] ?? 'datetimepicker';
?>" name="<?php echo $input['name'];
?>" value="<?php echo $this->fieldsValue[$input['name']] ?? '';?>" />
<span class="input-group-addon"><i class="icon-calendar-empty"></i></span>
</div>
</div>
<?php
}

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ ALL INPUT COMMON
if (isset($input['desc'])) {?>
<p class="form-text text-muted">
<?php
    if (is_array($input['desc'])) {
        foreach($input['desc'] as $value) {
            if (is_array($value)) {?>
<span id="<?php echo $value['id'];?>"><?php
            echo $value['text'];?></span><br />
<?php
            } else {
                echo $value;?><br />
<?php
            }
        }
    } else {
        echo $input['desc'];
    }
?>
</p>
<?php
}
?>
</div>
<?php }?>
</div>
<?php }?>
</div>
<?php
}}

//#################################################### COMMON BUTTON
if (isset($fieldSet['form']['submit']) || isset($fieldSet['form']['buttons'])) {?>
<div class="panel-footer"><?php
    if (isset($fieldSet['form']['submit'])) {
?><button type="submit" value="1" id="<?php
        echo $this->controller.'_form_submit_btn';
?>_1" name="<?php
        echo $fieldSet['form']['submit']['name'];
?>" class="<?php
        echo $fieldSet['form']['submit']['class'] ?? 'btn btn-default pull-right';
?>"><i class="<?php
        echo $fieldSet['form']['submit']['icon'] ?? 'process-icon-save';?>"></i><?php
        echo $fieldSet['form']['submit']['title'];
?></button>
<?php
    }
    if (!empty($this->showCancelButton)) {
?><a href="#" class="btn btn-default"<?php
        if ($this->controller) {echo ' id="'.$this->controller.'_form_cancel_btn"';}
?> onclick="window.history.back();"><i class="process-icon-cancel"></i>Cancel</a>
<?php
    }
    if (isset($fieldSet['form']['reset'])) {
?><button type="reset" id="<?php
        echo $fieldSet['form']['reset']['id'] ?? $this->controller.'_form_reset_btn';
?>" class="<?php
        echo $fieldSet['form']['reset']['class'] ?? 'btn btn-default';?>"><?php
        if (isset($fieldSet['form']['reset']['icon'])) {
?><i class="<?php
            echo $fieldSet['form']['reset']['icon'];?>"></i><?php
        }
        echo $fieldSet['form']['reset']['title'];
?></button>
<?php
    }
    foreach($fieldSet['form']['buttons'] ?? [] as $btn) {
        if (isset($btn['href'])) {?>
<a href="<?php echo $btn['href'];?>"<?php
            if (isset($btn['id'])) {?> id="<?php echo $btn['id'];?>"<?php }
?> class="btn btn-default <?php echo $btn['class'] ?? '';?>"<?php
            if (isset($btn['js'])) {?> onclick="<?php echo $btn['js'];?>"<?php }
?>><?php
            if (isset($btn['icon'])) {?><i class="<?php echo $btn['icon'];?>" ></i><?php }
            echo $btn['title'];
?></a>
<?php
        } else {
?><button type="<?php
            echo $btn['type'] ?? 'button';?>"<?php
            if (isset($btn['id'])) {?> id="<?php echo $btn['id'];?>"<?php }
?> class="btn btn-default <?php echo $btn['class'] ?? '';?>" name="<?php
            echo $btn['name'] ?? 'submitOptions'.$this->controller;?>"<?php
            if (isset($btn['js'])) {?> onclick="<?php echo $btn['js'];?>"<?php }
?>><?php
            if (isset($btn['icon'])) {?><i class="<?php echo $btn['icon'];?>" ></i><?php }
            echo $btn['title'];
?></button>
<?php
        }
    }
?></div><?php
}
?></div><?php }?></form>
<script type="text/javascript"></script>