<div class="leftside-menu">
    <a href="/" class="logo text-center logo-light">
                    <span class="logo-lg">
                        <img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" height="32">
                    </span>
        <span class="logo-sm">
                        <img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" height="32">
                    </span>
    </a>
    <a href="/" class="logo text-center logo-dark">
                    <span class="logo-lg">
                        <img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" height="32">
                    </span>
        <span class="logo-sm">
                        <img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" height="32">
                    </span>
    </a>

    <div class="h-100" id="leftside-menu-container" data-simplebar>
        <ul class="side-nav">
            <?php foreach ($this->menus as $menu) {?>
                <li class="side-nav-item">
                    <a data-bs-toggle="collapse" href="#m<?php echo $menu['id'];?>" aria-expanded="false" aria-controls="m<?php echo $menu['id'];?>" class="side-nav-link">
                        <i class="uil-<?php echo $menu['icon'];?>"></i><span class="menu-arrow"></span><span> <?php echo $menu['name'];?> </span>
                    </a>
                    <div class="collapse" id="m<?php echo $menu['id'];?>">
                        <ul class="side-nav-second-level"><?php foreach ($menu['childs'] as $menu) {
                            ?><li><a href="<?php echo $menu['url'];?>"><?php echo $menu['name'];?></a></li><?php
                        }?></ul>
                    </div>
                </li>
            <?php }?>
        </ul>
        <div class="clearfix"></div>

    </div>
</div>