<?php echo \Hook\Hook\Hook::run('displayTop');?>
<!DOCTYPE html>
<html lang="<?php echo AbstractModel::getData('hp_lang', $_SESSION[APP_NAME]['lang_id'] ?? APP_LANG)['lang'];?>">
<head>
<meta charset="utf-8" /><meta name="theme-color" content="#3063A0"><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon.png"><link rel="shortcut icon" href="/favicon.ico">
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
<link rel="stylesheet" href="/assets/stylesheets/main.min.css">
<link rel="stylesheet" href="/assets/vendor/flatpickr/flatpickr.min.css">
<link rel="stylesheet" href="/assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
<?php echo \Hook\Hook\Hook::run('displayHead');?>