<?php echo \Hook\Hook\Hook::run('displayTop');?>
<!DOCTYPE html>
<html lang="<?php echo $_SESSION[APP_NAME]['language_code'] ?? 'zh-cn';?>">
<head>
<meta charset="utf-8" />
<meta name="theme-color" content="#3063A0"><meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<base href="<?php echo APP_CONFIG['http']['uri'];?>" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/apple-touch-icon.png"><link rel="shortcut icon" href="assets/favicon.ico">
<script src="assets/vendor/jquery/jquery.min.js"></script><script src="assets/vendor/pace/pace.min.js"></script>
<link rel="stylesheet" href="assets/vendor/pace/pace.min.css"><link rel="stylesheet" href="assets/vendor/bootstrap/css/bootstrap.min.css"><link rel="stylesheet" href="assets/vendor/open-iconic/css/open-iconic-bootstrap.min.css"><link rel="stylesheet" href="assets/vendor/fontawesome/css/fontawesome.all.css">
<link rel="stylesheet" href="assets/stylesheets/main.min.css"><link rel="stylesheet" href="assets/stylesheets/custom.css">
<?php echo \Hook\Hook\Hook::run('displayHead');?>