<?php require __DIR__.'/../top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<h1>Error</h1>
<pre><?php echo $this->exception->getMessage(); ?></pre>
<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
<?php require __DIR__.'/../bottom.phtml';?>