<?php require __DIR__ . '/../top.phtml'; ?>
<title><?php echo $this->title; ?></title>
<meta name="description" content="<?php echo $this->description; ?>"/>
<meta name="keywords" content="<?php echo $this->keywords; ?>"/>
<link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style"/>
</head>
<body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'>
<div class="auth-fluid">
    <div class="auth-fluid-form-box">
        <div class="align-items-center d-flex h-100">
            <div class="card-body">
                <div class="auth-brand text-center text-lg-start">
                    <a href="javascript: void(0);" class="logo-dark">
                        <span><img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" height="18"></span>
                    </a>
                    <a href="javascript: void(0);" class="logo-light">
                        <span><img src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" height="18"></span>
                    </a>
                </div>
                <div id="reset_password">
                    <h4 class="mt-0">Reset Password</h4>
                    <p class="text-muted mb-4">Enter your email address and we'll send you an email with instructions to reset your password.</p>
                    <form class="needs-validation">
                        <div class="mb-3">
                            <label for="emailaddress" class="form-label">Email address</label>
                            <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                        </div>
                        <div class="mb-0 text-center d-grid">
                            <button class="btn btn-primary" type="submit"><i class="mdi mdi-lock-reset"></i> Reset Password </button>
                        </div>
                    </form>
                    <footer class="footer footer-alt">
                        <p class="text-muted">Back to <a href="/login" class="text-muted ms-1"><b>Log In</b></a></p>
                    </footer>
                </div>
                <div id="check_email" style="display: none">
                    <div class="text-center m-auto">
                        <img src="/assets/images/mail_sent.svg" alt="mail sent image" height="64" />
                        <h4 class="text-dark-50 text-center mt-4 fw-bold">Please check your email</h4>
                        <p class="text-muted mb-4">
                            A email has been send to <b>youremail@domain.com</b>.
                            Please check for an email from company and click on the included link to
                            reset your password.
                        </p>
                    </div>
                    <div class="mb-0 d-grid text-center">
                        <a class="btn btn-primary" href="/"><i class="mdi mdi-home me-1"></i> Back to Home </a>
                    </div>
                    <footer class="footer footer-alt">
                        <p class="text-muted">2018 - <script>document.write(new Date().getFullYear())</script> © HookPHP - <?php echo $this->title;?></p>
                    </footer>
                </div>
            </div>
        </div>
    </div>
    <div class="auth-fluid-right text-center">
        <div class="auth-user-testimonial">
            <h2 class="mb-3">I love the HookPHP!</h2>
            <p class="lead"><i class="mdi mdi-format-quote-open"></i> <?php echo $this->title;?>! . <i class="mdi mdi-format-quote-close"></i></p>
            <p>- LetWang</p>
        </div>
    </div>
</div>
<script src="/assets/js/vendor.min.js"></script>
<script src="/assets/js/app.min.js"></script>
<script>
    $('.needs-validation').submit(function (event) {
        event.preventDefault();
        if (!$(this)[0].checkValidity()) {
            event.stopPropagation();
        } else {
            $('#reset_password').hide();
            $('#check_email').show();
        }
        $(this).addClass('was-validated');
    });
</script>
<?php require __DIR__ . '/../bottom.phtml'; ?>