<?php require APP_PATH.'/layout/head.phtml';?>

<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
	<div class="container">
		<div class="error"><?php echo "Error Msg:" . $this->exception->getMessage();?></div>
	</div>
<?php require APP_PATH.'/layout/foot.phtml';?>