<?php require APP_ROOT.'/views/'.APP_THEME.'/top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="app">
    <?php require APP_ROOT.'/views/'.APP_THEME.'/head.phtml';?>
    <?php require APP_ROOT.'/views/'.APP_THEME.'/left.phtml';?>
    <main class="app-main">
        <div class="wrapper">
          <div class="page">
            <div class="page-inner">
              <?php require APP_ROOT.'/views/'.APP_THEME.'/table.phtml';?>
            </div>
          </div>
        </div>
        <?php require APP_ROOT.'/views/'.APP_THEME.'/foot.phtml';?>
    </main>
</div>
<script type="text/javascript">advanceDataTables.init('/api/menu/v1/', [
    { data: 'id', className: 'col-checker align-middle', orderable: false, searchable: false },
    { data: { _: 'app_id', sort: 'app_id', search: 'app_id' }, className: 'align-middle' },
    { data: 'parent', className: 'align-middle' },
    { data: 'status', className: 'align-middle' },
    { data: 'position', className: 'align-middle' },
    { data: 'date_add', className: 'align-middle' },
    { data: 'date_upd', className: 'align-middle' },
    { data: 'url', className: 'align-middle' },
    { data: 'icon', className: 'align-middle' },
    { data: 'id', className: 'align-middle text-right', orderable: false, searchable: false }
],{
    targets: 0,
    render: function render(data, type, row, meta) {
      return '<div class="custom-control custom-control-nolabel custom-checkbox">\n<input type="checkbox" class="custom-control-input" name="selectedRow[]" id="p' + row.id + '" value="' + row.id + '">\n<label class="custom-control-label" for="p' + row.id + '"></label>\n</div>';
    }
  }, {
    targets: 1,
    render: function render(data, type, row, meta) {
      return '<a href="#' + row.id + '" class="tile tile-img mr-1">\n</a>\n<a href="#' + row.id + '">' + row.name + '</a>';
    }
  }, {
    targets: 6,
    render: function render(data, type, row, meta) {
      return '<a class="btn btn-sm btn-secondary" href="#' + data + '"><i class="fa fa-pencil-alt"></i></a>\n<a class="btn btn-sm btn-secondary" href="#' + data + '"><i class="far fa-trash-alt"></i></a>';
    }
  });</script>
<?php require APP_ROOT.'/views/'.APP_THEME.'/bottom.phtml';?>