<?php require APP_ROOT.'/views/'.APP_THEME.'/top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="app">
  <?php require APP_ROOT.'/views/'.APP_THEME.'/head.phtml';?>
  <?php require APP_ROOT.'/views/'.APP_THEME.'/left.phtml';?>
  <main class="app-main">
    <div class="wrapper">
      <div class="page">
        <div class="page-inner">
          <header class="page-title-bar">
            <!-- page title stuff goes here -->
          </header>
          <div class="page-section">
            Index
          </div>
        </div>
      </div>
    </div>
    <?php require APP_ROOT.'/views/'.APP_THEME.'/foot.phtml';?>
  </main>
</div>
<?php require APP_ROOT.'/views/'.APP_THEME.'/bottom.phtml';?>